# config-defaults.yaml
# sample config defaults file
---
model_save_path: model_files/model.pth
data_source_config:
    desc: Pertaining to data sources
    input_sketch_path: model_input/sketches
    input_original_path: model_input/originals
    condition_path: model_input/conditions.npy
data_config:
    desc: Pertaining to the size of inputs and outputs
    input_size: 
        - 128
        - 128
    output_size:
        - 128
        - 128
    projection_size: 256
    condition_size: 15
    num_img: 100
    validation_sample_size: 1
    train_split: 0.9
wandb_config:
    desc: Pertaining to the experiment tracking
    project_name: sketch-VAE
    model_name: metrics_testing
    dataset_name: baseline_test_versioning
    artifact_name: test-model
    artifact_type: model
image_gen_config:
    desc: Pertaining to image generation
    gen_img: True
    simple_sketch_path: generation_input/holdout_sketches_simple
    detail_sketch_path: generation_input/holdout_sketches_detailed
    holdout_photo_path: generation_input/holdout_photos

    bad_sketch_path: generation_input/bad_sketches
    bad_photo_path: generation_input/bad_photos

    cuhk_sketch_path: generation_input/CUHK_sketches
    cuhk_photo_path: generation_input/CUHK_photos
    gen_with_condition: 
sweep_config:
    method: random
    parameters:
        optimizer:
            values:
                - rmsprop
        epochs: 
            value: 2
        learning_rate:
            distribution: uniform
            min: 0.0
            max: 0.006
        batch_size: 
            value: 128

    


  
