# config-defaults.yaml
# sample config defaults file
---
data_source_info:
  desc: Pertaining to data sources
  source: npy_files/sketches.npy
  target: npy_files/originals.npy
  condition: 
model_info:
  desc: Pertaining to architecture
  condition: True
  condition_type: mul
  skip_connection: True
data_info:
  desc: Pertaining to the size of inputs and outputs
  input_size: 
    - 128
    - 128
  output_size:
    - 268
    - 268
  condition_size: 1024
  num_img: 100
training_info:
  desc: Pertaining to how the model is trained
  train_split: 0.8
  epochs: 5
  batch_size: 128
  learning_rate: 0.01
  gen_img: 
  test_img_path: test.jpg
  save_path: model_files/model.pth
wandb_info:
  desc: Pertaining to the experiment tracking
  model_name: sketch-VAE
  architecture: VAE
  dataset: beta
  artifact_name: test-model
  artifact_type: model


  
